version: 2
jobs:
  build:
    docker:
    # primary container - all steps are executed in the first container that is listed
      - image: souadmin/champaign-deploy:0.0.7
    # secondary containers
      - image: circleci/postgres:9.4.11-alpine
      - image: redis

    steps:
      - checkout

      # TODO: add opts to restore cache
      - restore_cache:
        key: champaign-{{ checksum "Gemfile.lock" }}

      - restore_cache:
        key: champaign-{{ checksum "yarn.lock" }}

      # bundle install
      - run: bundle check || bundle install --without development --jobs=4 --retry=3

      - save_cache:
        key: champaign-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      - run:
        name: yarn
        command: yarn

      - save_cache:
        key: champaign-{{ checksum "yarn.lock" }}
        paths:
          - node_modules

      - run:
        name: database
        command: bundle exec rake RAILS_ENV=test db:create db:migrate db:seed champaign:seed_liquid

      - run:
        name: assets
        # changed from downloading assets to downloading and precompiling
        command: RAILS_ENV=production bundle exec rake assets:download_and_precompile[$EXTERNAL_ASSET_PATHS,$CUSTOM_ASSETS_URL,$CUSTOM_ASSETS_CREDENTIALS,$CIRCLE_BRANCH]

      - run:
        name: test
        command: yarn run flow check && yarn run test && bundle exec rspec spec

#
#deployment:
#  production:
#    branch: 'master'
#    commands:
#      - BRAINTREE_TOKEN_URL=$PRODUCTION_BRAINTREE_TOKEN_URL ./bin/build.sh
#      - ./bin/deploy.sh $CIRCLE_SHA1 'champaign' 'env-production-1' 'champaign-assets-production' 'logs3.papertrailapp.com:44107' 'actions.sumofus.org'
#  staging:
#    branch:  'development'
#    commands:
#      - BRAINTREE_TOKEN_URL=$STAGING_BRAINTREE_TOKEN_URL ./bin/build.sh
#      - ./bin/deploy.sh $CIRCLE_SHA1 'champaign' 'env-staging' 'champaign-assets-staging' 'logs3.papertrailapp.com:34848' 'action-staging.sumofus.org'
#
#  testing:
#    branch:  'testing'
#    commands:
#      - BRAINTREE_TOKEN_URL=$STAGING_BRAINTREE_TOKEN_URL ./bin/build.sh
#      - ./bin/deploy.sh $CIRCLE_SHA1 'champaign' 'env-feature' 'champaign-assets-testing' 'logs3.papertrailapp.com:34848' 'testing.sumofus.org'
